{% set name = "cw2" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cw2-{{ version }}.tar.gz
  sha256: c57bb8005f8a6aefab6dba4d38146c72c5c97a169c044b593d7d407053128aa4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - numpy
    - pandas
    - joblib

test:
  imports:
    - cw2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ALRhub/cw2
  summary: A reengineered framework to run experiments on a computing cluster.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
